version: "3.8"
services:
  feds:
    container_name: feds
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    env_file:
      - .env
